apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/DogWitDaButter/GitOps-Demo.git
    targetRevision: main
    path: manifests/sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
